// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED encoder generated by util/design/secded_gen.py

module prim_secded_16_11_enc (
  input        [10:0] data_i,
  output logic [15:0] data_o
);

  always_comb begin : p_encode
    data_o = 16'(data_i);
    data_o[11] = ^(data_o & 16'h043F);
    data_o[12] = ^(data_o & 16'h05C7);
    data_o[13] = ^(data_o & 16'h06D9);
    data_o[14] = ^(data_o & 16'h076A);
    data_o[15] = ^(data_o & 16'h07B4);
  end

endmodule : prim_secded_16_11_enc
