// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED encoder generated by util/design/secded_gen.py

module prim_secded_15_10_enc (
  input        [9:0] data_i,
  output logic [14:0] data_o
);

  always_comb begin : p_encode
    data_o = 15'(data_i);
    data_o[10] = ^(data_o & 15'h003F);
    data_o[11] = ^(data_o & 15'h01C7);
    data_o[12] = ^(data_o & 15'h02D9);
    data_o[13] = ^(data_o & 15'h036A);
    data_o[14] = ^(data_o & 15'h03B4);
  end

endmodule : prim_secded_15_10_enc
